version: '3'

services:
  app:
    image: myapp:latest
    ports:
      - "5000:5000"
    volumes:
      - myapp_data:/app/data
    networks:
      - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - app_network

volumes:
  myapp_data:
  db_data:

networks:
  app_network:
